param(
    [string]$SdkDir = "$env:LOCALAPPDATA\Android\Sdk",
    [string]$Jdk17Dir = "",
    [switch]$SkipSdkInstall,
    [switch]$SkipSubmodule,
    [switch]$SkipBuild,
    [switch]$InstallApk,
    [switch]$LaunchApp
)

$ErrorActionPreference = "Stop"

function Write-Step([int]$Index, [int]$Total, [string]$Text) {
    Write-Host ""
    Write-Host "[$Index/$Total] $Text"
}

function Get-JavaMajor([string]$JavaExe) {
    $output = cmd /c "`"$JavaExe`" -version 2>&1"
    if ($LASTEXITCODE -ne 0 -and -not $output) {
        return -1
    }
    $line = ($output | Select-Object -First 1)
    if ($line -notmatch '"([^"]+)"') {
        return -1
    }
    $raw = $Matches[1]
    $parts = $raw.Split(".")
    $major = 0
    if ($parts[0] -eq "1" -and $parts.Length -gt 1) {
        [void][int]::TryParse($parts[1], [ref]$major)
    }
    else {
        [void][int]::TryParse($parts[0], [ref]$major)
    }
    return $major
}

function Find-Jdk17([string]$RequestedDir) {
    $candidates = New-Object System.Collections.Generic.List[string]

    if ($RequestedDir) { $candidates.Add($RequestedDir) }
    if ($env:JAVA_HOME) { $candidates.Add($env:JAVA_HOME) }

    $common = @(
        "C:\Program Files\Android\Android Studio\jbr",
        "C:\Program Files\Java\jdk-17",
        "C:\Program Files\Eclipse Adoptium\jdk-17*",
        "E:\Java\develop\jdk",
        "D:\Java\jdk-17"
    )
    foreach ($p in $common) {
        if ($p.Contains("*")) {
            Get-ChildItem -Path $p -Directory -ErrorAction SilentlyContinue | ForEach-Object { $candidates.Add($_.FullName) }
        }
        else {
            $candidates.Add($p)
        }
    }

    $javaFromPath = (& where.exe java 2>$null)
    foreach ($javaPath in $javaFromPath) {
        if ($javaPath) {
            $dir = Split-Path -Parent (Split-Path -Parent $javaPath)
            if ($dir) { $candidates.Add($dir) }
        }
    }

    foreach ($dir in $candidates) {
        if (-not $dir) { continue }
        $javaExe = Join-Path $dir "bin\java.exe"
        if (-not (Test-Path $javaExe)) { continue }
        $major = Get-JavaMajor $javaExe
        if ($major -eq 17) {
            return $dir
        }
    }

    return ""
}

function Find-SdkManager([string]$AndroidSdkDir) {
    $candidates = @(
        (Join-Path $AndroidSdkDir "cmdline-tools\latest\bin\sdkmanager.bat"),
        (Join-Path $AndroidSdkDir "cmdline-tools\latest\bin\sdkmanager"),
        (Join-Path $AndroidSdkDir "cmdline-tools\bin\sdkmanager.bat"),
        (Join-Path $AndroidSdkDir "cmdline-tools\bin\sdkmanager")
    )
    foreach ($c in $candidates) {
        if (Test-Path $c) { return $c }
    }

    $sdkManagerCmd = Get-Command sdkmanager -ErrorAction SilentlyContinue
    if ($null -ne $sdkManagerCmd) { return $sdkManagerCmd.Source }

    return ""
}

function Find-Adb([string]$AndroidSdkDir) {
    $candidates = @(
        (Join-Path $AndroidSdkDir "platform-tools\adb.exe"),
        (Join-Path $AndroidSdkDir "platform-tools\adb")
    )
    foreach ($c in $candidates) {
        if (Test-Path $c) { return $c }
    }

    $adbCmd = Get-Command adb -ErrorAction SilentlyContinue
    if ($null -ne $adbCmd) { return $adbCmd.Source }

    return ""
}

function Ensure-LocalProperties([string]$RepoRoot, [string]$AndroidSdkDir) {
    $path = Join-Path $RepoRoot "local.properties"
    $sdkEscaped = ($AndroidSdkDir -replace "\\", "\\\\")
    $sdkLine = "sdk.dir=$sdkEscaped"

    if (-not (Test-Path $path)) {
        $content = @(
            "# Auto-generated by tools/dev/windows-bootstrap.ps1",
            $sdkLine,
            "",
            "# Optional for GitHub OAuth features:",
            "# GITHUB_CLIENT_ID=iv1_xxx",
            "# GITHUB_CLIENT_SECRET=xxx"
        )
        Set-Content -Path $path -Value $content -Encoding UTF8
        return
    }

    $lines = Get-Content -Path $path -Encoding UTF8
    $found = $false
    for ($i = 0; $i -lt $lines.Count; $i++) {
        if ($lines[$i] -match "^\s*sdk\.dir\s*=") {
            $lines[$i] = $sdkLine
            $found = $true
            break
        }
    }

    if (-not $found) {
        $lines += ""
        $lines += $sdkLine
    }

    Set-Content -Path $path -Value $lines -Encoding UTF8
}

function Add-ToPathIfMissing([string]$Value) {
    if (-not $Value) { return }
    $parts = $env:PATH -split ";"
    if ($parts -notcontains $Value) {
        $env:PATH = "$Value;$env:PATH"
    }
}

function Resolve-SdkDir([string]$InputSdkDir) {
    $candidates = New-Object System.Collections.Generic.List[string]
    if ($InputSdkDir) { $candidates.Add($InputSdkDir) }
    if ($env:ANDROID_SDK_ROOT) { $candidates.Add($env:ANDROID_SDK_ROOT) }
    if ($env:ANDROID_HOME) { $candidates.Add($env:ANDROID_HOME) }
    $candidates.Add("$env:LOCALAPPDATA\Android\Sdk")
    $candidates.Add("D:\Android\Sdk")
    $candidates.Add("E:\Android\Sdk")
    $candidates.Add("H:\Android\Sdk")
    $candidates.Add("C:\Android\Sdk")

    foreach ($c in $candidates) {
        if (-not $c) { continue }
        if (Test-Path $c) { return $c }
    }

    return $InputSdkDir
}

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$gradlew = Join-Path $repoRoot "gradlew.bat"
$apkPath = Join-Path $repoRoot "app\build\outputs\apk\debug\app-debug.apk"
$SdkDir = Resolve-SdkDir $SdkDir

$totalSteps = 7
$step = 1

Write-Host "MetaAgent Windows Bootstrap"
Write-Host "Repo: $repoRoot"

Write-Step $step $totalSteps "Choose JDK 17"
$step++
$jdk = Find-Jdk17 $Jdk17Dir
if (-not $jdk) {
    throw @"
JDK 17 not found.
Please install JDK 17, then rerun:
powershell -ExecutionPolicy Bypass -File .\tools\dev\windows-bootstrap.ps1 -Jdk17Dir "C:\Path\To\JDK17"
"@
}
$env:JAVA_HOME = $jdk
Add-ToPathIfMissing (Join-Path $jdk "bin")
Write-Host "Using JDK 17: $jdk"

Write-Step $step $totalSteps "Check Android SDK and sdkmanager"
$step++
if (-not (Test-Path $SdkDir)) {
    throw @"
Android SDK directory not found: $SdkDir
Please install Android Studio and SDK packages once, then rerun.
"@
}

$sdkManager = Find-SdkManager $SdkDir
if (-not $sdkManager) {
    if ($SkipSdkInstall) {
        Write-Host "sdkmanager not found, but SkipSdkInstall is set. Continuing."
    }
    else {
        throw @"
sdkmanager not found under: $SdkDir
Install Android Command-line Tools in Android Studio SDK Manager, then rerun.
"@
    }
}

$env:ANDROID_HOME = $SdkDir
$env:ANDROID_SDK_ROOT = $SdkDir
Add-ToPathIfMissing (Join-Path $SdkDir "cmdline-tools\latest\bin")
Add-ToPathIfMissing (Join-Path $SdkDir "platform-tools")
Write-Host "Using SDK: $SdkDir"
if ($sdkManager) {
    Write-Host "Using sdkmanager: $sdkManager"
}

Write-Step $step $totalSteps "Install required Android SDK packages"
$step++
if (-not $SkipSdkInstall) {
    $required = @(
        "platform-tools",
        "platforms;android-34",
        "build-tools;34.0.0",
        "ndk;27.0.12077973",
        "cmake;3.22.1"
    )

    cmd /c "echo y| `"$sdkManager`" --licenses >nul"
    & $sdkManager @required
    if ($LASTEXITCODE -ne 0) {
        throw "sdkmanager package install failed with code $LASTEXITCODE"
    }
}
else {
    Write-Host "Skip SDK package installation."
}

Write-Step $step $totalSteps "Generate or update local.properties"
$step++
Ensure-LocalProperties $repoRoot $SdkDir
Write-Host "Updated local.properties with sdk.dir"

Write-Step $step $totalSteps "Sync submodules"
$step++
if (-not $SkipSubmodule) {
    Push-Location $repoRoot
    try {
        & git submodule sync --recursive
        if ($LASTEXITCODE -ne 0) { throw "git submodule sync failed: $LASTEXITCODE" }
        & git submodule update --init --recursive
        if ($LASTEXITCODE -ne 0) { throw "git submodule update failed: $LASTEXITCODE" }
    }
    finally {
        Pop-Location
    }
}
else {
    Write-Host "Skip submodule sync."
}

Write-Step $step $totalSteps "Build debug APK"
$step++
if (-not $SkipBuild) {
    if (-not (Test-Path $gradlew)) { throw "gradlew.bat not found: $gradlew" }

    Push-Location $repoRoot
    try {
        & $gradlew "assembleDebug" "--no-daemon" "--stacktrace" "--console" "plain"
        if ($LASTEXITCODE -ne 0) {
            throw @"
Gradle build failed.
If you see TLS handshake errors, check proxy/VPN/firewall and try Android Studio sync once.
"@
        }
    }
    finally {
        Pop-Location
    }
}
else {
    Write-Host "Skip build."
}

Write-Step $step $totalSteps "Optional install and launch"
$step++
if ($InstallApk -or $LaunchApp) {
    if (-not (Test-Path $apkPath)) {
        throw "APK not found: $apkPath"
    }

    $adb = Find-Adb $SdkDir
    if (-not $adb) {
        throw "adb not found. Install platform-tools or fix SDK path."
    }

    & $adb devices
    if ($LASTEXITCODE -ne 0) { throw "adb devices failed" }

    if ($InstallApk) {
        & $adb install -r -d $apkPath
        if ($LASTEXITCODE -ne 0) { throw "adb install failed: $LASTEXITCODE" }
    }
    if ($LaunchApp) {
        & $adb shell monkey -p com.ai.assistance.metaagent 1
        if ($LASTEXITCODE -ne 0) { throw "app launch failed: $LASTEXITCODE" }
    }
}
else {
    Write-Host "Skip install/launch (pass -InstallApk and/or -LaunchApp to enable)."
}

Write-Host ""
Write-Host "Bootstrap finished."
Write-Host "APK: $apkPath"
